services:
  postgres:
    image: postgres:15
    container_name: autopool_postgres
    restart: always
    environment:
      POSTGRES_USER: autopool_user
      POSTGRES_PASSWORD: autopool_pass
      POSTGRES_DB: autopool_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-redis:
    image: redis:7
    container_name: autopool_auth_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - auth_redis_data:/data

  driver-location-redis:
    image: redis:7
    container_name: autopool_driver_location_redis
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - driver_location_redis_data:/data

  request-trip-redis:
    image: redis:7
    container_name: autopool_request_trip_redis
    restart: always
    ports:
      - "6382:6379"
    volumes:
      - request_trip_redis_data:/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: autopool_cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - postgres

volumes:
  postgres_data:
  auth_redis_data:
  profile_redis_data:
  driver_location_redis_data:
  request_trip_redis_data:
  cloudbeaver_data:
